UICIRC-992: Also support feesfines interface version 19.0
folio-org/ui-circulation pull request #1080
Opened 2023-10-11 12:07 UTC by Dmitriy-Litvinenko

## Purpose
Also support `feesfines` interface version `19.0`

## Approach
Changes was in endpoint `/accounts` that do not used in current component

## Refs
https://issues.folio.org/browse/UICIRC-992

2023-10-11 13:11 UTC, zburke requested changes
The new interface support looks fine, but assuming this is supposed to land if v9, you need to fix the CHANGELOG entry. Or if this _is_ intended for v10 then you need to bump the version in `package.json` too.

2023-10-12 08:37 UTC, Dmitriy-Litvinenko commented
@zburke Could you please review (package.json updated)? Current pull request will be merged after release previous release.

2023-10-12 20:06 UTC, zburke approved these changes
👌 Adding a new version of an existing interface is fine in a minor version. The thing that's tricky is removing supported versions, e.g. changing from 
```
"feesfines": "16.2 17.0 18.0"
```
to
```
"feesfines": "16.3 17.0 18.0"
```
is a breaking change because you're removing support for something you used to handle.

2023-10-13 10:02 UTC, artem-blazhko approved these changes

2023-10-18 11:49 UTC, merged