UICIRC-698: Create new setting for title level requests
folio-org/ui-circulation pull request #804
Opened 2021-10-06 06:47 UTC by Stanislau-Snapok

## Purpose
Create new setting for title level requests

## Approach
In scope of this task new settings was added. New components fully covered with RTL/Jest tests.

### This PR should be merged after https://issues.folio.org/browse/UICIRC-699 will merge!

## Refs
https://issues.folio.org/browse/UICIRC-698

## Screenshots
![image](https://user-images.githubusercontent.com/88130496/136153287-c2d04205-6117-4b0b-83d9-fdae8bb5750e.png)
![image](https://user-images.githubusercontent.com/88130496/136153463-4eb6e7d9-949a-40c1-9f38-eb301b4e6e02.png)

2021-10-06 14:06 UTC, Dmitriy-Litvinenko requested changes

2021-10-07 06:57 UTC, Stanislau-Snapok commented on src/constants.js
> +export const TITLE_LEVEL_REQUESTS_PROPS_IDS = {
done

2021-10-07 06:57 UTC, Stanislau-Snapok commented on src/settings/TitleLevelRequests/NoticeTemplates/NoticeTemplates.js
> +    { value: 'null', label: 'Select notice' },
done

2021-10-07 06:57 UTC, Stanislau-Snapok commented on src/settings/TitleLevelRequests/NoticeTemplates/NoticeTemplates.js
> +  const valuesForChoise = [
done

2021-10-07 06:57 UTC, Stanislau-Snapok commented on src/settings/TitleLevelRequests/utils/getInitialValues.js
> +    config = { ...TITLE_LEVEL_REQUESTS_FORM_DEFAULT_PROPS, ...JSON.parse(value) };
refactored

2021-10-08 13:51 UTC, merged