UICIRC-865: Removed unused file.
folio-org/ui-circulation pull request #990
Opened 2023-01-23 17:00 UTC by Dmitriy-Litvinenko

## Purpose
Removed unused file

## Approach
This file is not used, so it has been removed from the project.

## Refs
https://issues.folio.org/browse/UICIRC-865

2023-01-24 05:37 UTC, Terala-Priyanka requested changes
Could you please fix the linting issues? - one has arrived due to your changes, and the other is already there.

2023-01-24 13:46 UTC, Dmitriy-Litvinenko commented
Hello @Terala-Priyanka Could you please re-review?

2023-01-25 05:11 UTC, Terala-Priyanka approved these changes

2023-01-25 11:52 UTC, artem-blazhko approved these changes

2023-01-25 12:28 UTC, merged